name: ğŸš€ Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VER: 22

    services:
      # docker run --name durabletask-sidecar -p 4001:4001 --env 'DURABLETASK_SIDECAR_LOGLEVEL=Debug' --rm cgillum/durabletask-sidecar:latest start --backend Emulator
      durabletask-sidecar:
        image: cgillum/durabletask-sidecar:latest
        ports:
          - 4001:4001
        env:
          DURABLETASK_SIDECAR_LOGLEVEL: Debug
          DURABLETASK_STORAGE_PROVIDER: Emulator

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: âš™ï¸ NodeJS - Install
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          registry-url: "https://registry.npmjs.org"

      - name: âš™ï¸ Install dependencies
        run: npm install

      - name: ğŸ”¨ Build packages
        run: npm run build

      - name: âœ… Run unit tests
        run: npm run test:unit

      - name: âœ… Run e2e tests
        run: npm run test:e2e
